//update this regularly
var vertexNamesReference = [
  "AS1",
  "AS2",
  "AS3",
  "AS4",
  "AS5",
  "AS6",
  "AS7",
  "AS8",
  "Ameens",
  "BIZ1",
  "BIZ2",
  "Basketball Courts",
  "CELC",
  "CFA Studios",
  "COM1",
  "COM2",
  "Cendana College",
  "Central Library",
  "Central Library Annexe",
  "Centre for Life Sciences",
  "Centre for Maritime Studies",
  "Chinese Library",
  "Chua Thian Poh Hall",
  "Cinnamon College",
  "College of Alice & Peter Tan",
  "Computer Centre",
  "Create",
  "Create Tower",
  "DSO @ Kent Ridge",
  "E1",
  "E1A",
  "E2",
  "E2A",
  "E3",
  "E3A",
  "E4",
  "E4A",
  "E5",
  "E6",
  "EA",
  "EW1",
  "EW2",
  "Education Resource Centre",
  "Elm College",
  "Engineering Auditorium",
  "Eusoff Hall",
  "Faculty of Dentistry",
  "Football Field",
  "Frontier",
  "Handball, Netball Courts",
  "Hon Sui Sen Memorial Library",
  "House 3",
  "House 4",
  "House 5, BTC",
  "House 17",
  "House 18",
  "I3",
  "Institute of Materials Research & Engineering",
  "Institute of South East Asian Studies",
  "Institute of Systems Science",
  "KE VII Hall",
  "Kent RIdge Terminal",
  "Kent Ridge Guild House",
  "Kent Ridge Hall",
  "Kent Ridge MRT",
  "Lecture Theatre 1",
  "Lecture Theatre 2",
  "Lecture Theatre 3",
  "Lecture Theatre 4",
  "Lecture Theatre 5",
  "Lecture Theatre 6",
  "Lecture Theatre 7",
  "Lecture Theatre 7A",
  "Lecture Theatre 8",
  "Lecture Theatre 9",
  "Lecture Theatre 10",
  "Lecture Theatre 11",
  "Lecture Theatre 12",
  "Lecture Theatre 13",
  "Lecture Theatre 14",
  "Lecture Theatre 15",
  "Lecture Theatre 16",
  "Lecture Theatre 17",
  "Lecture Theatre 18",
  "Lecture Theatre 19",
  "Lecture Theatre 20",
  "Lecture Theatre 21",
  "Lecture Theatre 22",
  "Lecture Theatre 24",
  "Lecture Theatre 25",
  "Lecture Theatre 26",
  "Lecture Theatre 27",
  "Lecture Theatre 28",
  "Lecture Theatre 29",
  "Lecture Theatre 31",
  "Lecture Theatre 32",
  "Lecture Theatre 33",
  "Lecture Theatre 34",
  "Lecture Theatre 37",
  "Lee Kong Chian Natural History Museum",
  "Lovers' Park",
  "MD1",
  "MD2",
  "MD3",
  "MD4",
  "MD4A",
  "MD5",
  "MD6",
  "MD7",
  "MD8",
  "MD9",
  "MD10",
  "MD11",
  "MPSH 1, MPSH 2, MPSH 3, MPSH 4",
  "MPSH 5",
  "MPSH 6",
  "McDonald's",
  "Medical Library",
  "Multi-Purpose Fields",
  "NUH",
  "NUH Kent Ridge Wing",
  "NUH Medical Centre",
  "NUH Service Block",
  "NUHS Tower Block",
  "National University Center of Oral Health",
  "PGP Terminal",
  "Prince George's Park Residences",
  "Raffles Hall",
  "Residential College 4",
  "Ridge View Residences",
  "S1",
  "S1A",
  "S2",
  "S2S",
  "S3",
  "S4",
  "S4A",
  "S5",
  "S6",
  "S7",
  "S8",
  "S9",
  "S9A",
  "S10",
  "S11",
  "S12",
  "S13",
  "S14",
  "S15",
  "S16",
  "S17",
  "SDE1",
  "SDE2",
  "SDE3",
  "SDE4",
  "Saga College",
  "Science Library",
  "Shaw Foundation Alumni House",
  "Sheares Hall",
  "Singapore Synchrotron Light Source",
  "Singapore Wind Tunnel Facility",
  "Sports and Recreation Centre",
  "Staff Club",
  "Stephen Riady Centre",
  "T-Lab",
  "Techno Edge",
  "Temasek Hall",
  "Tembusu College",
  "Tennis Courts",
  "The Deck",
  "The Ngee Ann Kongsi Auditorium",
  "The Terrace",
  "Town Green",
  "Town Plaza",
  "UTown Residences",
  "University Cultural Centre",
  "University Hall",
  "University Health Centre",
  "Ventus",
  "Visitors' Lodge",
  "Yale-NUS College",
  "Yale-NUS College Library",
  "Yong Siew Toh Conservatory of Music",
  "Yusof Ishak House"
]
